apiVersion: v1
kind: Namespace
metadata:
  name: team_1
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: team_1
  name: team_1-rw
rules:
- apiGroups: ["extensions", "apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: team_1
  name: team_1-binding
subjects:
- kind: Group
  name: team_1@fourcast.io
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: team_1-rw
  apiGroup: rbac.authorization.k8s.io


  